name: "MindsDB CLA Assistant"

permissions:
  actions: read
  contents: write
  pull-requests: write
  statuses: write

on:
  issue_comment:
    types: [created]
  pull_request_target:
    types: [opened,closed,synchronize]

jobs:
  CLAssistant:
    uses: mindsdb/github-actions/.github/workflows/cla-assistant.yml@main
    with:
      path-to-signatures: 'assets/contributions-agreement/cla.json'
      path-to-document: 'https://github.com/mindsdb/mindsdb/blob/main/assets/contributions-agreement/individual-contributor.md'
      allowlist: bot*, ZoranPandovski, torrmal, Stpmax, mindsdbadmin, ea-rus, tmichaeldb, dusvyat, hamishfagg, MinuraPunchihewa, martyna-mindsdb, lucas-koontz
